export const LANGS_LIST_LOAD = 'LANGS_LIST_LOAD'
export const LANGS_LIST_SELECT_LANG = 'LANGS_LIST_SELECT_LANG'
export const LANGS_LIST_CHANGE_LANG = 'LANGS_LIST_CHANGE_LANG'
export const LANGS_LIST_CLEAR = 'LANGS_LIST_CLEAR'
