export const LANGS_LIST_LOAD = 'LANGS_LIST_LOAD'
export const LANGS_LIST_SELECT_LANG = 'LANGS_LIST_SELECT_LANG'
export const LANGS_LIST_CHANGE_LANG = 'LANGS_LIST_CHANGE_LANG'
export const LANGS_LIST_CLEAR = 'LANGS_LIST_CLEAR'

export const COMMANDS_LIST_LOAD = 'COMMANDS_LIST_LOAD'
export const COMMANDS_LIST_LOAD_SUCCESS = 'COMMANDS_LIST_LOAD_SUCCESS'
export const COMMANDS_LIST_LOAD_FILED = 'COMMANDS_LIST_LOAD_FILED'
export const COMMANDS_LIST_CLEAR = 'COMMANDS_LIST_CLEAR'
